# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время и дата создания')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('expires_in', models.BigIntegerField(verbose_name='Истекает в течение')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'токен',
                'verbose_name_plural': 'токены',
            },
        ),
    ]
