# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161029_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='user',
        ),
        migrations.AddField(
            model_name='public',
            name='access_token',
            field=models.CharField(default='', max_length=200, verbose_name='Токен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='public',
            name='like',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Лайки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='public',
            name='minute',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Минуты'),
            preserve_default=False,
        ),
    ]
