# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161119_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
